# Generated by Django 4.2 on 2023-11-16 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('discrition', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 16, 20, 52, 57, 426830, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
