# Generated by Django 4.2 on 2023-11-16 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlesmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 16, 20, 54, 49, 675395, tzinfo=datetime.timezone.utc)),
        ),
    ]
